application: countmeinbot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(sendMessage|editMessageText|editMessageReplyMarkup)
  script: main.app
  login: admin
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: "2.7.11"
